### ISSUE TITLE
Error with build

### ISSUE THREAD

**Issue by NikitaSavc** [AOSPA/android_build_soong#2]
```
[ 99% 395/396] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / &&  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
Clang SA is not enabled
error: prebuilts/clang/host/linux-x86/Android.bp:370:1: module "llvm-tools": module source path "prebuilts/clang/host/linux-x86/clang-r450784d/bin/llvm-symbolizer" does not exist
error: prebuilts/clang/host/linux-x86/Android.bp:370:1: module "llvm-tools": module source path "prebuilts/clang/host/linux-x86/clang-r450784d/bin/llvm-cxxfilt" does not exist
error: prebuilts/clang/host/linux-x86/Android.bp:370:1: module "llvm-tools": module source path "prebuilts/clang/host/linux-x86/clang-r450784d/lib64/libc++.so.1" does not exist
```
Hello, i have this error on Cirrus CI, when i try build AOSPA Topaz for Xiaomi Redmi Note 5(Whyred). 
What's to do???

**Comment by xboxfanj** [comment]
Have not seen this, can you sync again?

**Comment by NikitaSavc** [comment]
@xboxfanj I tried resync three times

**Comment by xboxfanj** [comment]
Seems like your lunch may not be succeeding.  Can you send me the full output?

**Comment by NikitaSavc** [comment]
@xboxfanj https://github.com/ROM-builders/temporary/pull/18724
https://cirrus-ci.com/task/6513751579426816

**Comment by orges** [comment]
Try removing https://github.com/9QS/android_device_xiaomi_whyred/blob/8b2b1779d5bb96fe9e32f64f41c003a4313beafd/BoardConfig.mk#L54

**Comment by NikitaSavc** [comment]
@orges I will try remove it, thank you. I'll come back later.

**Comment by NikitaSavc** [comment]
@xboxfanj @orges https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/4d52068718fb7940b103cc49506f77e5d22f25df
Bruh. Maybe it's problem? :/

**Comment by orges** [comment]
I don't think so, everything exists in my source. Could be a sync problem or misconfiguration

**Comment by orges** [comment]
Just followed the ci build, you definitely have sync issue

**Comment by NikitaSavc** [comment]
@orges Removing flag didn't help. 
My build_rom.sh:
https://github.com/9QS/temporary/blob/main/build_rom.sh

**Comment by xboxfanj** [comment]
I am not sure your repo init groups are correct.  Can you try not specifying groups?

**Comment by NikitaSavc** [comment]
@xboxfanj i will try, thanks.

**Comment by NikitaSavc** [comment]
@xboxfanj I can't to do it.
```
set -e
curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/test.sh | bash
Please use --depth=1 and -g default,-mips,-darwin,-notdefault tags in repo init line.
```
Cirrus CI do not apply my build

**Comment by NikitaSavc** [comment]
Sorry. It's problem of Cirrus CI. Thank you!
